# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

lines = [
  'City Terminal Zone',
  'Babylon',
  'Far Rockaway',
  'Hempstead',
  'Long Beach',
  'Montauk',
  'Oyster Bay',
  'Port Jefferson',
  'Port Washington',
  'Ronkonkoma',
  'West Hempstead'
]

lines.each do |line|
  Line.create(name: line)
end

towns = [
  {town: "Woodside", line: "City Terminal Zone"},
  {town: "Forest Hills", line: "City Terminal Zone"},
  {town: "Kew Gardens", line: "City Terminal Zone"},
  {town: "Flatbush Ave", line: "City Terminal Zone"},
  {town: "Nostrand Ave", line: "City Terminal Zone"},
  {town: "East New York", line: "City Terminal Zone"},
  {town: "Jamacia", line: "City Terminal Zone"},
  {town: "Long Island City", line: "City Terminal Zone"},
  {town: "Hunterspoint Ave", line: "City Terminal Zone"},
  {town: "Long Island City", line: "City Terminal Zone"},
  {town: "Wooside", line: "City Terminal Zone"},
  {town: "Shea Stadium", line: "Port Washington"},
  {town: "Flushing Main St", line: "Port Washington"},
  {town: "Murrary Hill", line: "Port Washington"},
  {town: "Broadway", line: "Port Washington"},
  {town: "Auburndale", line: "Port Washington"},
  {town: "Bayside", line: "Port Washington"},
  {town: "Douglaston", line: "Port Washington"},
  {town: "Little Neck", line: "Port Washington"},
  {town: "Great Neck", line: "Port Washington"},
  {town: "Manhasset", line: "Port Washington"},
  {town: "Plandome", line: "Port Washington"},
  {town: "Port Washington", line: "Port Washington"},
  {town: "Holis", line: "Hempstead"},
  {town: "Queens Village", line: "Hempstead"},
  {town: "Bellerose", line: "Hempstead"},
  {town: "Floral Park", line: "Hempstead"},
  {town: "Stewart Manor", line: "Hempstead"},
  {town: "Nassau Blvd", line: "Hempstead"},
  {town: "Garden City", line: "Hempstead"},
  {town: "Country Life Press", line: "Hempstead"},
  {town: "Hempstead", line: "Hempstead"},

  {town: "Lynbrook", line: "test"},

  {town: "Centre Ave", line: "Long Beach"},
  {town: "East Rockaway", line: "Long Beach"},
  {town: "Oceanside", line: "Long Beach"},
  {town: "Island Park", line: "Long Beach"},
  {town: "Long Beach", line: "Long Beach"},
  {town: "Locust Manor", line: "Far Rockaway"},
  {town: "Laurelton", line: "Far Rockaway"},
  {town: "Laurelton", line: "Far Rockaway"},
  {town: "Valley Stream", line: "Far Rockaway"},
  {town: "Gibson", line: "Far Rockaway"},
  {town: "Hewlett", line: "Far Rockaway"},
  {town: "Woodmere", line: "Far Rockaway"},
  {town: "Cedarhurst", line: "Far Rockaway"},
  {town: "Lawrence", line: "Far Rockaway"},
  {town: "Inwood", line: "Far Rockaway"},
  {town: "Far Rockaway", line: "Far Rockaway"},
  {town: "Rockville Centre", line: "Babylon"},
  {town: "Baldwin", line: "Babylon"},
  {town: "Freeport", line: "Babylon"},
  {town: "Merrick", line: "Babylon"},
  {town: "Bellmore", line: "Babylon"},
  {town: "Wantagh", line: "Babylon"},
  {town: "Seaford", line: "Babylon"},
  {town: "Massapequa", line: "Babylon"},
  {town: "Massapequa Park", line: "Babylon"},
  {town: "Amityville", line: "Babylon"},
  {town: "Copiague", line: "Babylon"},
  {town: "Lindenhurst", line: "Babylon"},
  {town: "Babylon", line: "Babylon"},
  {town: "St.Albans", line: "West Hempstead"},
  {town: "Westwood", line: "West Hempstead"},
  {town: "Malverne", line: "West Hempstead"},
  {town: "Lakeview", line: "West Hempstead"},
  {town: "Hempstead Gardens", line: "West Hempstead"},
  {town: "West Hempstead", line: "West Hempstead"},

  {town: "Bethpage", line: "test"},

  {town: "Bay Shore", line: "Montauk"},
  {town: "Islip", line: "Montauk"},
  {town: "Great River", line: "Montauk"},
  {town: "Oakdale", line: "Montauk"},
  {town: "Sayville", line: "Montauk"},
  {town: "Patchogue", line: "Montauk"},
  {town: "Bellport", line: "Montauk"},
  {town: "Mastic-Shirley", line: "Montauk"},
  {town: "Speonk", line: "Montauk"},
  {town: "Westhampton", line: "Montauk"},
  {town: "Hampton Bays", line: "Montauk"},
  {town: "Southhampton", line: "Montauk"},
  {town: "Bridgehampton", line: "Montauk"},
  {town: "East Hampton", line: "Montauk"},
  {town: "Amagansett", line: "Montauk"},
  {town: "Montauk", line: "Montauk"},
  
  {town: "Hicksville", line: "test"},

  {town: "Farmingdale", line: "Greenport"},
  {town: "Pinelawn", line: "Greenport"},
  {town: "Wyandanch", line: "Greenport"},
  {town: "Deer Park", line: "Greenport"},
  {town: "Brentwood", line: "Greenport"},
  {town: "Central Islip", line: "Greenport"},
  {town: "Ronkonkoma", line: "Greenport"},
  {town: "Medford", line: "Greenport"},
  {town: "Yaphank", line: "Greenport"},
  {town: "Riverhead", line: "Greenport"},
  {town: "Mattituck", line: "Greenport"},
  {town: "Southold", line: "Greenport"},
  {town: "Greenport", line: "Greenport"},
  
  {town: "Queens Village", line: "test"},
  
  {town: "New Hyde Park", line: "Port Jefferson"},
  {town: "Merillon Ave", line: "Port Jefferson"},
  {town: "Mineola", line: "Port Jefferson"},
  {town: "Carle Place", line: "Port Jefferson"},
  {town: "Westbury", line: "Port Jefferson"},
  {town: "Hicksville", line: "Port Jefferson"},
  {town: "Syosset", line: "Port Jefferson"},
  {town: "Cold Spring Harbor", line: "Port Jefferson"},
  {town: "Huntington", line: "Port Jefferson"},
  {town: "Greenlawn", line: "Port Jefferson"},
  {town: "Northport", line: "Port Jefferson"},
  {town: "Kings Park", line: "Port Jefferson"},
  {town: "Smithtown", line: "Port Jefferson"},
  {town: "St. James", line: "Port Jefferson"},
  {town: "Stony Brook", line: "Port Jefferson"},
  {town: "Port Jefferson", line: "Port Jefferson"},
  {town: "Mineola", line: "Oyster Bay"},
  {town: "East Williston", line: "Oyster Bay"},
  {town: "Albertson", line: "Oyster Bay"},
  {town: "Rosyln", line: "Oyster Bay"},
  {town: "Greenvale", line: "Oyster Bay"},
  {town: "Glen Head", line: "Oyster Bay"},
  {town: "Sea Cliff", line: "Oyster Bay"},
  {town: "Glen St", line: "Oyster Bay"},
  {town: "Glen Cove", line: "Oyster Bay"},
  {town: "Locust Valley", line: "Oyster Bay"},
  {town: "Oyster Bay", line: "Oyster Bay"}]